version: '3'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  mongo-express:
      image: mongo-express
      depends_on:
          - mongodb
      ports:
        - "8888:8081"
      environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin
volumes:
  mongodb-data: